apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-work-app.fullname" . }}
  labels:
    {{- include "hello-work-app.labels" . | nindent 4 }}
data:
  ADDRESS: "0.0.0.0"
  PORT: "3000"
