apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-work-app.fullname" . }}
  labels:
    {{- include "hello-work-app.labels" . | nindent 4 }}
type: Opaque
data:
  A_SECRET_VALUE: {{ .Values.aSecretValue | b64enc }}
